const auth = require("../controller/employeeController");
const authJwt = require("../middleware/authJwt");
const { upload, FranchiseUpload, productUpload } = require('../middleware/imageupload')
module.exports = (app) => {
        app.post('/api/v1/employee/signin', auth.signin);
        app.get('/api/v1/employee/getProfile', authJwt.verifyToken, auth.getProfile);
        app.get('/api/v1/employee/getPatient', authJwt.verifyToken, auth.getPatient);
        app.put('/api/v1/employee/updateProfile', authJwt.verifyToken, upload.single('image'), auth.updateProfile);
        app.post('/api/v1/employee/addEmployeeApplication', authJwt.verifyToken, auth.addEmployeeApplication);
        app.get('/api/v1/employee/viewEmployeeApplication', authJwt.verifyToken, auth.viewEmployeeApplication);
        app.get('/api/v1/employee/viewEmployeeApplicationByEmployeeId/:employeeId', authJwt.verifyToken, auth.viewEmployeeApplicationByEmployeeId);
        app.post('/api/v1/employee/addEmployeeEducation', authJwt.verifyToken, auth.addEmployeeEducation);
        app.get('/api/v1/employee/viewEmployeeEducation', authJwt.verifyToken, auth.viewEmployeeEducation);
        app.get('/api/v1/employee/viewEmployeeEducationByEmployeeId/:employeeId', authJwt.verifyToken, auth.viewEmployeeEducationByEmployeeId);
        app.post('/api/v1/employee/addEmployeeHistory', authJwt.verifyToken, auth.addEmployeeHistory);
        app.get('/api/v1/employee/viewEmployeeHistory', authJwt.verifyToken, auth.viewEmployeeHistory);
        app.get('/api/v1/employee/viewEmployeeHistoryByEmployeeId/:employeeId', authJwt.verifyToken, auth.viewEmployeeHistoryByEmployeeId);
        app.post('/api/v1/employee/addEmployeeOtherInfo', authJwt.verifyToken, auth.addEmployeeOtherInfo);
        app.get('/api/v1/employee/viewEmployeeOtherInfo', authJwt.verifyToken, auth.viewEmployeeOtherInfo);
        app.get('/api/v1/employee/viewEmployeeOtherInfoByEmployeeId/:employeeId', authJwt.verifyToken, auth.viewEmployeeOtherInfoByEmployeeId);
        app.post('/api/v1/employee/addEmployeeSkillAndQualification', authJwt.verifyToken, auth.addEmployeeSkillAndQualification);
        app.get('/api/v1/employee/viewEmployeeSkillAndQualification', authJwt.verifyToken, auth.viewEmployeeSkillAndQualification);
        app.get('/api/v1/employee/viewEmployeeSkillAndQualificationByEmployeeId/:employeeId', authJwt.verifyToken, auth.viewEmployeeSkillAndQualificationByEmployeeId);
        app.post('/api/v1/employee/createVisitLog', authJwt.verifyToken, auth.createVisitLog);
        app.get('/api/v1/employee/getAllVisitLog', authJwt.verifyToken, auth.getAllVisitLog);
        app.get('/api/v1/employee/getAllVisitLogByEmployeeId/:employeeId', authJwt.verifyToken, auth.getAllVisitLogByEmployeeId);
        app.get('/api/v1/employee/getVisitLogById/:id', authJwt.verifyToken, auth.getVisitLogById);
        app.put('/api/v1/employee/updateVisitLog/:id', authJwt.verifyToken, auth.updateVisitLog);
        app.delete('/api/v1/employee/deleteVisitLog/:id', authJwt.verifyToken, auth.deleteVisitLog);
        app.post('/api/v1/employee/createMileageLog', authJwt.verifyToken, auth.createMileageLog);
        app.get('/api/v1/employee/getAllMileageLog', authJwt.verifyToken, auth.getAllMileageLog);
        app.get('/api/v1/employee/getAllMileageLogByEmployeeId/:employeeId', authJwt.verifyToken, auth.getAllMileageLogByEmployeeId);
        app.get('/api/v1/employee/getMileageLogById/:id', authJwt.verifyToken, auth.getMileageLogById);
        app.put('/api/v1/employee/updateMileageLog/:id', authJwt.verifyToken, auth.updateMileageLog);
        app.delete('/api/v1/employee/deleteMileageLog/:id', authJwt.verifyToken, auth.deleteMileageLog);
        app.post('/api/v1/StaffSchedule/add', authJwt.verifyToken, auth.addStaffSchedule);
        app.get('/api/v1/StaffSchedule/getStaffSchedule', authJwt.verifyToken, auth.getStaffSchedule);
        app.get('/api/v1/StaffSchedule/getStaffScheduleByEmployeeId/:employeeId', authJwt.verifyToken, auth.getStaffScheduleByEmployeeId);
        app.post('/api/v1/employee/createEmployeeInServiceLog', authJwt.verifyToken, auth.createEmployeeInServiceLog);
        app.get('/api/v1/employee/getAllEmployeeInServiceLog', authJwt.verifyToken, auth.getAllEmployeeInServiceLog);
        app.get('/api/v1/employee/getAllEmployeeInServiceLogByEmployeeId/:employeeId', authJwt.verifyToken, auth.getAllEmployeeInServiceLogByEmployeeId);
        app.get('/api/v1/employee/getEmployeeInServiceLogById/:id', authJwt.verifyToken, auth.getEmployeeInServiceLogById);
        app.put('/api/v1/employee/updateEmployeeInServiceLog/:id', authJwt.verifyToken, auth.updateEmployeeInServiceLog);
        app.delete('/api/v1/employee/deleteEmployeeInServiceLog/:id', authJwt.verifyToken, auth.deleteEmployeeInServiceLog);
        app.post('/api/v1/employee/createOnSiteFacility', authJwt.verifyToken, auth.createOnSiteFacility);
        app.get('/api/v1/employee/getAllOnSiteFacility', authJwt.verifyToken, auth.getAllOnSiteFacility);
        app.get('/api/v1/employee/getAllOnSiteFacilityByEmployeeId/:employeeId', authJwt.verifyToken, auth.getAllOnSiteFacilityByEmployeeId);
        app.get('/api/v1/employee/getOnSiteFacilityById/:id', authJwt.verifyToken, auth.getOnSiteFacilityById);
        app.put('/api/v1/employee/updateOnSiteFacility/:id', authJwt.verifyToken, auth.updateOnSiteFacility);
        app.delete('/api/v1/employee/deleteOnSiteFacility/:id', authJwt.verifyToken, auth.deleteOnSiteFacility);
        app.post('/api/v1/employee/createSkillAndKnowledge', authJwt.verifyToken, auth.createSkillAndKnowledge);
        app.get('/api/v1/employee/getAllSkillAndKnowledge', authJwt.verifyToken, auth.getAllSkillAndKnowledge);
        app.get('/api/v1/employee/getAllSkillAndKnowledgeByEmployeeId/:employeeId', authJwt.verifyToken, auth.getAllSkillAndKnowledgeByEmployeeId);
        app.get('/api/v1/employee/getSkillAndKnowledgeById/:id', authJwt.verifyToken, auth.getSkillAndKnowledgeById);
        app.put('/api/v1/employee/updateSkillAndKnowledge/:id', authJwt.verifyToken, auth.updateSkillAndKnowledge);
        app.delete('/api/v1/employee/deleteSkillAndKnowledge/:id', authJwt.verifyToken, auth.deleteSkillAndKnowledge);
        app.get('/api/v1/employee/getAllBhrfTherapyTopic', auth.getAllBhrfTherapyTopic);
        app.post('/api/v1/employee/createTherapySession', authJwt.verifyToken, auth.createTherapySession);
        app.get('/api/v1/employee/getAllTherapySession', authJwt.verifyToken, auth.getAllTherapySession);
        app.get('/api/v1/employee/getAllTherapySessionForResident', authJwt.verifyToken, auth.getAllTherapySessionForResident);
        app.get('/api/v1/employee/getAllTherapySessionByemployeeId/:employeeId', authJwt.verifyToken, auth.getAllTherapySessionByemployeeId);
        app.get('/api/v1/employee/getTherapySessionById/:id', authJwt.verifyToken, auth.getTherapySessionById);
        app.delete('/api/v1/employee/deleteTherapySession/:id', authJwt.verifyToken, auth.deleteTherapySession);
        app.post('/api/v1/employee/createTimeOffRequest', authJwt.verifyToken, auth.createTimeOffRequest);
        app.get('/api/v1/employee/getAllTimeOffRequest', authJwt.verifyToken, auth.getAllTimeOffRequest);
        app.get('/api/v1/employee/getTimeOffRequestById/:id', authJwt.verifyToken, auth.getTimeOffRequestById);
        app.delete('/api/v1/employee/deleteTimeOffRequest/:id', authJwt.verifyToken, auth.deleteTimeOffRequest);
        app.post('/api/v1/employee/createEmployeePerformanceReview', authJwt.verifyToken, auth.createEmployeePerformanceReview);
        app.get('/api/v1/employee/getAllEmployeePerformanceReview', authJwt.verifyToken, auth.getAllEmployeePerformanceReview);
        app.get('/api/v1/employee/getEmployeePerformanceReviewById/:id', authJwt.verifyToken, auth.getEmployeePerformanceReviewById);
        app.delete('/api/v1/employee/deleteEmployeePerformanceReview/:id', authJwt.verifyToken, auth.deleteEmployeePerformanceReview);
        app.post('/api/v1/employee/createPatientTracking', authJwt.verifyToken, auth.createPatientTracking);
        app.get('/api/v1/employee/getAllPatientTracking/:patientId', authJwt.verifyToken, auth.getAllPatientTracking);
        app.get('/api/v1/employee/getPatientTrackingById/:id', authJwt.verifyToken, auth.getPatientTrackingById);
        app.post('/api/v1/employee/createPatientVitals', authJwt.verifyToken, auth.createPatientVitals);
        app.get('/api/v1/employee/getPatientVitalsByPatientId/:patientId', authJwt.verifyToken, auth.getPatientVitalsByPatientId);

}